unique_ids:
  assets:
    standard-page.html: 2LIASGRBKBVBYDLEK4F4LYZ7HTY4QLNT
    theme.css: JCT7542DUGRXEK4TYC5VGFF5Q4Z25YSI
  forms:
    Form1: U64PE55AFRZXXCPFR2VKIJDYQWYV6KKR
  modules: {}
  scripts: {}
  server_modules: {}
