unique_ids:
  assets:
    standard-page.html: 2LIASGRBKBVBYDLEK4F4LYZ7HTY4QLNT
    theme.css: JCT7542DUGRXEK4TYC5VGFF5Q4Z25YSI
  forms:
    Default: U64PE55AFRZXXCPFR2VKIJDYQWYV6KKR
    GA4CreateProperty: '1730866381666728855335996.2'
    GA4UpdateProperty: '1730867164188998625769978.9629'
  modules: {}
  scripts: {}
  server_modules: {}
